# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin

name: MapBrowser
version: 1.0.0
main: com.tukuyomil032.mapbrowser.MapBrowserPlugin
api-version: '1.21.11'
authors: [tukuyomil032]
description: In-game web browser rendering plugin for Minecraft map screens.
softdepend: [PacketEvents, AnvilGUI, LuckPerms, Vault]

commands:
  mapbrowser:
    description: MapBrowser main command
    aliases: [mb]
    usage: /mapbrowser

permissions:
  mapbrowser.create:
    default: op
  mapbrowser.destroy:
    default: op
  mapbrowser.destroy.others:
    default: op
  mapbrowser.use:
    default: op
  mapbrowser.use.others:
    default: op
  mapbrowser.view:
    default: true
  mapbrowser.admin:
    default: op
  mapbrowser.bypass.whitelist:
    default: op
  mapbrowser.reload:
    default: op